### PR TITLE
Skip set-default-as-first-screen-100-roll-out

### PR DESCRIPTION
**Pull request by tdsmith**
We'd like to skip analyzing this experiment.

Anna, can you confirm that's also your understanding of what will happen here?

### CODE REVIEW

**Review by scholtzan — COMMENTED** [review]
I'm not sure. I think `enrollment_period =  -1` would work.

https://github.com/mozilla/jetstream/blob/b950a00f747dc64f12520982d65d5c96e7ceaaf2/jetstream/analysis.py#L56 adds +1 to `proposed_enrollment` (which is derived from the `enrollment_period`). So when [creating `TimeLimits`, no exception is raised](https://github.com/mozilla/mozanalysis/blob/25ab1609b5ffe1d1f4007df0b3f973ec3ea3c16f/src/mozanalysis/experiment.py#L771). Unless there is a check somewhere further downstream that I'm missing here.

**Comment by scholtzan** [comment]
Oh, also when `enrollment_period = 0`, wouldn't Jetstream just fallback to `proposed_enrollment` in https://github.com/mozilla/jetstream/blob/b950a00f747dc64f12520982d65d5c96e7ceaaf2/jetstream/config.py#L231 ?

**Comment by tdsmith** [comment]
Yeah, you're right, it'll just fall through.

I was trying to trip the check in check_runnable; -1 won't do that. https://github.com/mozilla/jetstream/blob/b950a00f747dc64f12520982d65d5c96e7ceaaf2/jetstream/analysis.py#L272

I guess we should either add `is_high_population` or something like `skip` or `ignore` to the config language. wdyt?

**Comment by scholtzan** [comment]
If we want to ignore the experiment for reasons other than it having a high population number, I'd prefer having an explicit `skip` in the config.

**Comment by tdsmith** [comment]
Should've seen that one coming.

**Comment by tdsmith** [comment]
Opened https://github.com/mozilla/jetstream/pull/549 to pass this with a green check.

**Pull request merged**
