### PR TITLE
Add search count for fenix

### PR DESCRIPTION
**Pull request by danielkberry**

### CODE REVIEW

**Comment by danielkberry** [comment]
@skahmann3

**Review by scholtzan — APPROVED** [review]

**Comment by danielkberry** [comment]
@scholtzan once these are merged, can we request a Jetstream rerun for https://experimenter.services.mozilla.com/nimbus/android-nightly-sponsored-shortcuts-validation/results#results_summary and https://experimenter.services.mozilla.com/nimbus/android-beta-sponsored-shortcuts-validation ?

**Comment by scholtzan** [comment]
yeah i can trigger the rerun for [https://experimenter.services.mozilla.com/nimbus/android-nightly-sponsored-shortcuts-validation](https://experimenter.services.mozilla.com/nimbus/android-nightly-sponsored-shortcuts-validation/results#results_summary)

https://experimenter.services.mozilla.com/nimbus/android-beta-sponsored-shortcuts-validation  seems to be still in the enrollment period, so it should pick up the new metrics by itself.

**Comment by skahmann3** [comment]
Can this be merged? Or do we need kik's review?

**Comment by kik-kik** [comment]
Apologies, I saw Anna already approved so I didn't do it.

**Comment by skahmann3** [comment]
Thanks all for your help on this! @scholtzan, when should I expect the re-run of [the Nightly experiment](https://experimenter.services.mozilla.com/nimbus/android-nightly-sponsored-shortcuts-validation/results) to be completed?

**Comment by scholtzan** [comment]
The next hour or so. The visualizations are usually updated nightly though, I can trigger a manual update if you need to see the most recent results.

**Comment by skahmann3** [comment]
I can wait until tomorrow for the visualizations/ most recent results. Thank you!

**Pull request merged**
